### ISSUE TITLE
Example of plug in usage with Oger

### ISSUE THREAD

**Issue by RichJackson** [OntoGene/OGER-filter#1]
Hi there

I'm trying to integrate OGER-filter with OGER. Can you provide an example of how the plugin can be configured to work at part of OGER?

**Comment by lfurrer** [comment]
Hi

OGER can take a callable as a postfilter, which OGER will call with an annotated document after the entity recognition step.
Here, [this function](https://github.com/OntoGene/OGER-filter/blob/aaf81263a44097643c6162f54ea44cc9eb02e64a/oger_nn_filter.py#L44) was used to disambiguate mentions with multiple annotations.

I'm sorry this isn't in the Readme.

**Comment by RichJackson** [comment]
Thanks - it worked

Note that I also needed to change

https://github.com/OntoGene/OGER-filter/blob/aaf81263a44097643c6162f54ea44cc9eb02e64a/oger_nn_filter.py#L27

to

```
CONFIG_PATH = os.path.join(HERE, 'CRAFT.ini')
```

complete example:
```
from oger.ctrl.router import Router, PipelineServer
params = {
"postfilter": ['<Path to Oger-filter repo>/OGER-filter/oger_nn_filter.py:disambiguate'],
"termlist_path":'<Path to Oger repo>/OGER/oger/test/testfiles/test_terms.tsv'

}

conf = Router(**params)
pl = PipelineServer(conf)
coll = pl.load_one(['21436587', '21436588','21436587'], fmt='pubmed')
pl.process(coll)
pl.postfilter(coll)


for doc in coll:
    for entity in doc.iter_entities():
        print(f"{entity.text}, {entity.type}, {entity.start}, {entity.end} ")
```
